projects:
    - name: Test
      path: C:\Users\wesle\dev\fortscript-dev\fortscript\teste.py

heavy_processes:
   # - name: Fortnite
   #   process: fortnite
  #  - name: Roblox
   #   process: roblox

ram_threshold: 90