projects:
  # - name: ProjectA
  #   path: C:\Users\dev\project\main.py
    - name: Obsidian
      path: C:\Users\wesle\AppData\Local\Programs\Obsidian\Obsidian.exe2

heavy_processes:
  # - name: Fortnite
  #   process: fortnite

ram_threshold: 90
